//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMCV_Model.DB68
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSign
    {
        public int DocumentSignID { get; set; }
        public int DocumentID { get; set; }
        public string DocumentReferenceCode { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public Nullable<int> SignIndex { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public Nullable<int> UserSignatureID { get; set; }
        public string UserEmpID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Note { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Page { get; set; }
    }
}
