//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMCV_Model.DB68
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int TagID { get; set; }
        public string TagName { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> Order { get; set; }
    }
}
